### PR TITLE
Development to Master

### PR DESCRIPTION
**Pull request by AaronStahley**
Latest commits from sprint 6 and 7 to master.

### CODE REVIEW

**Comment by cagloria** [comment]
Getting an error on Android when selecting start on any algorithm:
```
Invariant Violation: Invariant Violation: Invariant Violation: ScrollView child layout (["alignItems"]) must be applied through the contentContainerStyle prop.

This error is located at:
    in ScrollView (at ConversationScreen.js:56)
    in ConversationScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:60)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:60)
    in View (at StackViewLayout.js:400)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:60)
    in View (at Transitioner.js:141)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:38)
    in RCTView (at View.js:60)
    in View (at App.js:36)
    in Provider (at App.js:35)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

This error is located at:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:38)
    in RCTView (at View.js:60)
    in View (at App.js:36)
    in Provider (at App.js:35)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

This error is located at:
    in NavigationContainer (at App.js:38)
    in RCTView (at View.js:60)
    in View (at App.js:36)
    in Provider (at App.js:35)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

```

Changing line 58 in ConversationScreen to `contentContainerStyle={styles.root}` fixed it, though maybe you can check to make sure it still looks the way you wanted. Also, the PCH logo is shifted to the left on the home screen.

**Comment by AaronStahley** [comment]
@cagloria Are you running in an emulator or on a phone? Taylor was getting the same error as you but me and Conrad could run it fine. Also what API version are you on.

**Comment by cagloria** [comment]
That was on an emulator with API version 28. Waiting to test it on a phone with version 23.

**Comment by cagloria** [comment]
Same error on phone.

**Review by cagloria — APPROVED** [review]

**Pull request merged**
