### PR TITLE
Sprint7/us204/aaron

### PR DESCRIPTION
**Pull request by AaronStahley**
This pull request is for a major update in the conversation screen UI. I re-did everything to use the flex functionality built into React rather than the row and col system as before. The reason for this is that the row and col's where not responding well to different screen sizes as well as where hard to style. This is an almost finished UI state but will still need some additional tweaking after all data is entered into the app. 

I tested the functionality on but iOS and Android but would love if a few of you could review it. 

Thanks.

### CODE REVIEW

**Comment by cjmoraws** [comment]
ser402_app_box
This is kinda weird. Other question boxes allow you to click anywhere within but here you have to click the text to toggle it.

**Comment by AaronStahley** [comment]
I think I know what the issue is will try to fix today.

**Review by cjmoraws — APPROVED** [review]
Working w/ updated Expo, Android Studio.

**Comment by cjmoraws** [comment]
But need to smile more

**Pull request merged**
