### PR TITLE
Adding UpdateScreen

### PR DESCRIPTION
**Pull request by tgreeff**

### CODE REVIEW

**Review by AaronStahley — COMMENTED** [review]
Getting an error on iOS, also home screen is blank because of it. 

Screen Shot 2019-04-01 at 12 12 23 PM

Screen Shot 2019-04-01 at 12 13 37 PM

**Comment by AaronStahley** [comment]
Nevermind I might have fixed it. seems like for some reason the database in my emulator was corrupted somehow

**Comment by AaronStahley** [comment]
The pull-down refresh animation on the update screen is a little weird. It transitions from the default reload animation to the custom one and if the connection is fast it flickers on and off the screen too quickly.

**Comment by tgreeff** [comment]
Fixes seem good. I think that's good to move to dev

**Review by AaronStahley — APPROVED** [review]
Tested with an updated db in the support app and all pulls in fine.

**Pull request merged**
