### PR TITLE
Merge Sprint3/us43 taylor into development

### PR DESCRIPTION
**Pull request by tgreeff**

### CODE REVIEW

**Review by cagloria — COMMENTED** [review]
This might be due to the lack of resizing, but each message is slightly too big to the screen, which allows me to scroll each message back and forth horizontally by a few millimeters. I'm not sure if you plan to fix resizing by today.

**Comment by tgreeff** [comment]
That's odd. I don't have that issue with any of the devices that I tested with. What device did you use?

**Comment by cagloria** [comment]
Droid Maxx 2, has a resolution of 1920 x 1080.

**Comment by tgreeff** [comment]
I think the issue was due to the images not scaling based off of the size of the window, so that should fix it. If not, let me know.

**Comment by cagloria** [comment]
The images are now slightly cut off on the top and bottom, and the message bubbles are not scaling with the screen, being too short in length in landscape and too long in portrait.

**Comment by cagloria** [comment]
Okay, I've found the above is the problem if I start the app in landscape mode. If I start in portrait mode, it's fine, but when I then rotate to landscape, the content is too small, as if it kept the resolution.

**Comment by tgreeff** [comment]
The last issue was something that we can't do much with now because we need something called Mobx to refresh the screen when it is rotated. We're planning on adding that next sprint, so that should fix that issue, but i'll look into fixing the height of the image. That was something I'm not exactly sure how to fix, but I have some ideas. Also, thanks for looking at all of this I know it can be a pain sometimes

**Comment by cagloria** [comment]
No problem. If you can get that image fixed, I think it'll be good to merge for today.

**Comment by AaronStahley** [comment]
Hey, so it looks like the bubbles on the left and right (PCH Logo) of the conversation bubbles are expanding down as the conversation bubble gets larger. It looks more like an oval than a circle. Not sure if it's on iOS only but that is what I can see. Everything else looks fine style might need to be changed a bit but I think its okay to merge.

**Review by AaronStahley — APPROVED** [review]

**Comment by cagloria** [comment]
Icons look good on my device.

**Comment by tgreeff** [comment]
Awesome, should I wait for Aaron to check it on his phone or just merge it?

**Comment by cagloria** [comment]
It looks like his only comment was about the icons. He's already approved it and said it looks fine to merge.

**Comment by tgreeff** [comment]
Alright, that works for me. Thanks again

**Pull request merged**
